feature {
  name: "A_id"
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Acidity"
  type: BYTES
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "Crunchiness"
  type: FLOAT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Juiciness"
  type: FLOAT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Quality"
  type: BYTES
  domain: "Quality"
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Ripeness"
  type: FLOAT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Size"
  type: FLOAT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Sweetness"
  type: FLOAT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Weight"
  type: FLOAT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
string_domain {
  name: "Quality"
  value: "bad"
  value: "good"
}
